使用throw和try...catch語句

當在try區塊中的程式碼發生異常時，可以使用throw語句丟出異常，之後由catch區塊補獲

try區塊檢查是否產生例外，當例外產生，就使用throw拋出例外，catch區塊處理丟出的例外

```
try{
	
}catch(Exception $e){

}
```